name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Generate Deployment Package
        run: |
          mkdir -p deploy
          cp build/libs/*-SNAPSHOT.jar deploy/application.jar
          cd deploy && zip -r deploy.zip .

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: WeatherOfTheHeart
          environment_name: WeatherOfTheHeart-env
          # 👈 날짜/시간을 포함하여 매번 무조건 새로운 버전 이름 생성
          version_label: deploy-${{ env.date }}
          deployment_package: backend/deploy/deploy.zip
          wait_for_deployment: true